# Generated by Django 2.2.2 on 2019-06-23 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190621_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscriptions',
        ),
    ]
