# Generated by Django 2.2.2 on 2019-06-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Name of User'),
        ),
    ]
