# Generated by Django 2.2.2 on 2019-06-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20190623_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Post'),
        ),
    ]
