# Generated by Django 2.2.2 on 2019-06-23 23:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0005_auto_20190623_0741'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptions',
            unique_together={('user', 'subscribe_to')},
        ),
    ]
